jobs/urls.py
from django.urls import path
from jobs import views
from .views import *



urlpatterns = [
    path('', views.HomeView, name='home'),
    # path('jobs/', JobListView.as_view(), name='jobs'),
    path('jobss/', views.JobListView1, name='jobss'),
    path('categorylist/', views.categorylist, name='categorylist'),
    path('categoryjobs/<slug:slug_text>', views.categoryjobs, name='category-jobs'),
    path('locationlist/', views.locationlist, name='locationlist'),
    path('locationjobs/<slug:slug_text>', views.locationjobs, name='location-jobs'),
    path('job_details/<slug:slug_text>', views.job_details, name='job-details'),
    path('companylist/', views.companylist, name='companylist'),
    path('companyjobs/<slug:slug_text>', views.companyjobs, name='company-jobs'),
    path("applyjob/", views.applyjob, name="applyjob"),
    path('comingsoon/', views.comingsoon, name='commingsoon'),
    path('search', SearchView.as_view(), name='search'),
    path('postjob', views.postjob, name='postjob'),
    path('applications/', views.applications, name='applications'),
    path('myjobs/', views.myjobs, name='myjobs'),
    path('editjob/<slug:slug_text>', views.edit_job, name='editjob'),
    path('editjobpost', views.edit_job_post, name='editjobpost'),
    path('deletejob/<int:id>', views.del_job, name='deletejob'),

]

portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
    path('accounts/', include('accounts.urls')),
]

jobs/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import pre_save

# from accounts.models import User
from portal.suglify import unique_slug_generator

JOB_TYPE = (
    ('Full Time', "Full time"),
    ('Part time', "Part time"),
    ('Intership', "Internship"),
)

class Company(models.Model):
    title = models.CharField(max_length=500,default="paralleldesk")
    slug = models.SlugField(max_length=500,null=True,blank=True)
    company_address = models.TextField(null=True, blank=True)
    company_description = models.CharField(max_length=300)
    website = models.CharField(max_length=100, default="")
    email = models.EmailField(max_length=200, null=True, blank=True)
    phone = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title


class JobCategory(models.Model):
    title = models.CharField(max_length=500,default="System Admin")
    slug = models.SlugField(max_length=500,null=True,blank=True)
    date_posted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title



class Location(models.Model):
    title = models.CharField(max_length=500,default="Bangalore")
    slug = models.SlugField(max_length=500,null=True,blank=True)
    date_posted = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title


class Job(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=500)
    slug = models.SlugField(max_length=500,null=True,blank=True)
    description = models.TextField()
    type = models.CharField(choices=JOB_TYPE, max_length=10)
    last_date = models.DateField()
    created_at = models.DateTimeField(default=timezone.now)
    filled = models.BooleanField(default=False)
    salary = models.IntegerField(default=0, blank=True)
    category_type = models.ForeignKey(
        JobCategory, on_delete=models.CASCADE,
    )
    company_name = models.ForeignKey(
        Company, on_delete=models.CASCADE,
    )
    job_location = models.ForeignKey(
        Location, on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('job-details', args=[str(self.slug)])

class Applicant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='applicants')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.job



def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Job)
pre_save.connect(slug_generator, sender=JobCategory)
pre_save.connect(slug_generator, sender=Company)
pre_save.connect(slug_generator, sender=Location)
# class Applicant(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name='applicants')
#     created_at = models.DateTimeField(default=timezone.now)
#
#     def __str__(self):
#         return self.user.get_full_name()

templates/applications.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    All jobs
{% endblock %}

{% block content %}


<!-- Featured_job_start -->
    <div class="our-services " style="margin-top:80px;">
            <div class="container">
                   <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <h3 class="heading"><span class="accent">My job Applications</span></h3>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-xl-10">
                    {% for job in application %}
                        <!-- single-job-content -->
                        <div class="single-job-items mb-30">
                            <div class="job-items">
                                <div class="company-img">
                                    <a href="#"><img src="{% static 'img/icon/job-list1.png' %}" alt=""></a>
                                </div>
                                <div class="job-tittle">
                                    <a href="{% url 'job-details' job.job.slug %}"><h4>{{ job.job }}</h4></a>
                                    <ul>
                                         <li><i class="far fa-clock"></i> Applied at : {{ job.created_at|timesince }} </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="items-link f-right">
                                <a class="disabled">Applied</a>

                            </div>
                        </div>
                    {% endfor %}


       </div>
                </div>
            </div>
    </div>

{% endblock %}

templates/base.html
<!doctype html>
<html class="no-js" lang="zxx">
{% load static %}
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
         <title>Paralleldesk</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico'%}">

		<!-- CSS here -->
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
            <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
            <link rel="stylesheet" href="{% static 'css/price_rangs.css' %}">
            <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
            <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
            <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
            <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
            <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
            <link rel="stylesheet" href="{% static 'css/slick.css' %}">
            <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
            <link rel="stylesheet" href="{% static 'css/style.css' %}">

<style>
    .input-form{
    width:39% !important;
    }
         .data-background{
      width:10% important;
      }
</style>
    </head>

   <body>
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'img/logo/logo.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
       <div class="header-area header-transparrent">
           <div class="headder-top header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-2">
                            <!-- Logo -->
                            <div class="logo">
                                <a href="{% url 'home' %}"><img src="https://storage.googleapis.com/paralleldesk1sandbox1assets/images/ParallelDesk_Logo.jpg" width="250" alt=""></a>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <div class="menu-wrapper">
                                <!-- Main-menu -->
                                <div class="main-menu">
                                    <nav class="d-none d-lg-block">
                                        <ul id="navigation">
                                            <li><a href="#">Browse Jobs</a>
                                                <ul class="submenu">
                                                    <li><a href="{% url 'companylist' %}">Company Wise</a></li>
                                                    <li><a href="{% url 'locationlist' %}">Location Wise</a></li>
                                                    <li><a href="{% url 'categorylist' %}">Category Wise</a></li>
                                                    <li><a href="{% url 'jobss' %}">All Jobs</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Contact</a></li>
                                            {% if user.is_authenticated %}
                                                <li><a>{{user.username}}</a>
                                                            <ul class="submenu">
                                                                <li><a href="{% url 'myjobs' %}">My Jobs</a></li>
                                                                <li><a href="{% url 'applications' %}">My Applications</a></li>
                                                                <li><a href="{% url 'logout' %}">Logout</a></li>
                                                            </ul>
                                                </li>
                                                {% else %}
                                                  <li>  <a href="{% url 'register' %}" class="">Register</a></li>
                                                  <li>  <a href="{% url 'login' %}" class="">Login</a></li>
                                                {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                                <!-- Header-btn -->
                                <div class="header-btn d-none f-right d-lg-block">
                                         <li>  <a href="{% url 'postjob' %}" class="btn head-btn1">POST A JOB +</a></li>
                                </div>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
           </div>
       </div>
        <!-- Header End -->
    </header>
{% block content %} {% endblock %}
       <footer>
        <!-- Footer Start-->
        <div class="footer-area footer-bg footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                       <div class="single-footer-caption mb-50">
                         <div class="single-footer-caption mb-30">
                             <div class="footer-tittle">
                                 <h4>About Us</h4>
                                 <div class="footer-pera">
                                     <p>Heaven frucvitful doesn't cover lesser dvsays appear creeping seasons so behold.</p>
                                </div>
                             </div>
                         </div>

                       </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Contact Info</h4>
                                <ul>
                                    <li>
                                    <p>Address :Your address goes
                                        here, your demo address.</p>
                                    </li>
                                    <li><a href="#">Phone : +8880 44338899</a></li>
                                    <li><a href="#">Email : info@colorlib.com</a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Important Link</h4>
                                <ul>
                                    <li><a href="#"> View Project</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                    <li><a href="#">Testimonial</a></li>
                                    <li><a href="#">Proparties</a></li>
                                    <li><a href="#">Support</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Newsletter</h4>
                                <div class="footer-pera footer-pera2">
                                 <p>Heaven fruitful doesn't over lesser in days. Appear creeping.</p>
                             </div>
                             <!-- Form -->
                             <div class="footer-form" >
                                 <div id="mc_embed_signup">
                                     <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                     method="get" class="subscribe_form relative mail_part">
                                         <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                         class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                         onblur="this.placeholder = ' Email Address '">
                                         <div class="form-icon">
                                             <button type="submit" name="submit" id="newsletter-submit"
                                             class="email_icon newsletter-submit button-contactForm"><img src="{% static 'img/icon/form.png' %}" alt=""></button>
                                         </div>
                                         <div class="mt-10 info"></div>
                                     </form>
                                 </div>
                             </div>
                            </div>
                        </div>
                    </div>
                </div>
               <!--  -->

        <!-- footer-bottom area -->
        <div class="footer-bottom-area footer-bg">
            <div class="container">
                <div class="footer-border">
                     <div class="row d-flex justify-content-between align-items-center">
                         <div class="col-xl-10 col-lg-10 ">
                             <div class="footer-copy-right">
                                 <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy; All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="#" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                             </div>
                         </div>
                         <div class="col-xl-2 col-lg-2">
                             <div class="footer-social f-right">
                                 <a href="#"><i class="fab fa-facebook-f"></i></a>
                                 <a href="#"><i class="fab fa-twitter"></i></a>
                                 <a href="#"><i class="fas fa-globe"></i></a>
                                 <a href="#"><i class="fab fa-behance"></i></a>
                             </div>
                         </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
            </div></div> </footer>

  <!-- JS here -->

		<!-- All JS Custom Plugins Link Here here -->
        <script src="{% static '/js/vendor/modernizr-3.5.0.min.js' %}"></script>
		<!-- Jquery, Popper, Bootstrap -->
		<script src="{% static '/js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static '/js/popper.min.js' %}"></script>
        <script src="{% static '/js/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static '/js/jquery.slicknav.min.js' %}"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static '/js/owl.carousel.min.js' %}"></script>
        <script src="{% static '/js/slick.min.js' %}"></script>
        <script src="{% static '/js/price_rangs.js' %}"></script>

		<!-- One Page, Animated-HeadLin -->
        <script src="{% static '/js/wow.min.js' %}"></script>
		<script src="{% static '/js/animated.headline.js' %}"></script>
        <script src="{% static '/js/jquery.magnific-popup.js' %}"></script>

		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static '/js/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static '/js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static '/js/jquery.sticky.js' %}"></script>

        <!-- contact js -->
        <script src="{% static '/js/contact.js' %}"></script>
        <script src="{% static '/js/jquery.form.js' %}"></script>
        <script src="{% static '/js/jquery.validate.min.js' %}"></script>
        <script src="{% static '/js/mail-script.js' %}"></script>
        <script src="{% static '/js/jquery.ajaxchimp.min.js' %}"></script>

		<!-- Jquery Plugins, main Jquery -->
        <script src="{% static '/js/plugins.js' %}"></script>
        <script src="{% static '/js/main.js' %}"></script>

    </body>
</html>

templates/categorylist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <div class="our-services section-pad-t30">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <h2>Browse Top Categories </h2>
                        </div>
                    </div>
                </div>
                <div class="row d-flex justify-contnet-center">
                    {% for category in category_list %}
                    <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-services text-center mb-30">
                            <div class="services-ion">
                                <span class="flaticon-tour"></span>
                            </div>
                            <div class="services-cap">
                               <h5><a href="{% url 'category-jobs' category.slug %}">{{ category.title }}</a></h5>
                                <span></span>
                            </div>
                        </div>
                    </div>{% endfor %}  </div>

                    <div class="row">
           <div class="col-md-12">
               <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                 <ul class="pagination">
                {% if pagination.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link">&laquo;</a>
                    </li>
                     <li class="page-item">
                        <a href="?page={{ pagination.previous_page_number}}" class="page-link">&lsaquo;</a>
                    </li>
                {% else %}
                     <li class="page-item disabled">
                         <a class="page-link">&laquo;</a>
                     </li>
                      <li class="page-item disabled">
                         <a class="page-link">&lsaquo;</a>
                     </li>
                {% endif %}
                {% for i in pagination.paginator.page_range %}
                     {% if pagination.number == i %}
                       <li class="page-item active">
                           <p class="page-link"><strong >{{ i }}</strong></p>
                       </li>
                     {% elif i > pagination.number|add:'-2' and i < pagination.number|add:'2' %}
                       <li class="page-item">
                         <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                       </li>
                     {% endif %}
                 {% endfor %}
                 {% if pagination.has_next %}
                     <li class="page-item">
                        <a href="?page={{ pagination.next_page_number }}" class="page-link">&rsaquo;</a>
                     </li>
                     <li class="page-item">
                        <a href="?page={{ pagination.paginator.num_pages }}" class="page-link">&raquo;</a>
                     </li>
                   {% else %}
                         <li class="page-item disabled">
                        <a class="page-link">&rsaquo;</a>
                     </li>
                      <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                      </li>
                 {% endif %}
                 </ul></nav></div>
        </div>
                </div>
                <!-- More Btn -->
            </div></div>
        </div>


{% endblock %}

templates/companylist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="our-services t-30">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <span></span>
                            <h2>Browse Top Companines </h2>
                        </div>
                    </div>
                </div>
                <div class="row d-flex justify-contnet-center">
                     {% for company in company_list %}
                        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="single-services text-center mb-30">
                                <div class="services-ion">
                                    <span class="flaticon-tour"></span>
                                </div>
                                <div class="services-cap">
                                   <h5><a href="{% url 'company-jobs' company.slug %}">{{ company.title }}</a></h5>
                                    <span></span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}  </div>
        <div class="row">
           <div class="col-md-12">
               <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                 <ul class="pagination">
                {% if pagination.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link">&laquo;</a>
                    </li>
                     <li class="page-item">
                        <a href="?page={{ pagination.previous_page_number}}" class="page-link">&lsaquo;</a>
                    </li>
                {% else %}
                     <li class="page-item disabled">
                         <a class="page-link">&laquo;</a>
                     </li>
                      <li class="page-item disabled">
                         <a class="page-link">&lsaquo;</a>
                     </li>
                {% endif %}
                {% for i in pagination.paginator.page_range %}
                     {% if pagination.number == i %}
                       <li class="page-item active">
                           <p class="page-link"><strong >{{ i }}</strong></p>
                       </li>
                     {% elif i > pagination.number|add:'-2' and i < pagination.number|add:'2' %}
                       <li class="page-item">
                         <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                       </li>
                     {% endif %}
                 {% endfor %}
                 {% if pagination.has_next %}
                     <li class="page-item">
                        <a href="?page={{ pagination.next_page_number }}" class="page-link">&rsaquo;</a>
                     </li>
                     <li class="page-item">
                        <a href="?page={{ pagination.paginator.num_pages }}" class="page-link">&raquo;</a>
                     </li>
                   {% else %}
                         <li class="page-item disabled">
                        <a class="page-link">&rsaquo;</a>
                     </li>
                      <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                      </li>
                 {% endif %}
                 </ul></nav></div>
        </div>
                </div>
                <!-- More Btn --></div></div>
            </div>
        </div>

{% endblock %}

templates/locationlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

   <br><br><br>
               <!-- Our Services Start -->
        <div class="our-services">
            <div class="container">
                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center">
                            <span>FEATURED TOURS Packages</span>
                            <h2>Browse Top Locations </h2>
                        </div>
                    </div>
                </div>
                <div class="row d-flex justify-contnet-center">
                     {% for loaction in location_list %}
                        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="single-services text-center mb-30">
                                <div class="services-ion">
                                    <span class="flaticon-tour"></span>
                                </div>
                                <div class="services-cap">
                                   <h5><a href="{% url 'location-jobs' loaction.slug %}">{{ loaction.title }}</a></h5>
                                    <span></span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
    <div class="row">
           <div class="col-md-12">
           <center>    <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                 <ul class="pagination">
                {% if pagination.has_previous %}
                    <li class="page-item">
                        <a href="?page=1" class="page-link">&laquo;</a>
                    </li>
                     <li class="page-item">
                        <a href="?page={{ pagination.previous_page_number}}" class="page-link">&lsaquo;</a>
                    </li>
                {% else %}
                     <li class="page-item disabled">
                         <a class="page-link">&laquo;</a>
                     </li>
                      <li class="page-item disabled">
                         <a class="page-link">&lsaquo;</a>
                     </li>
                {% endif %}
                {% for i in pagination.paginator.page_range %}
                     {% if pagination.number == i %}
                       <li class="page-item active">
                           <p class="page-link"><strong >{{ i }}</strong></p>
                       </li>
                     {% elif i > pagination.number|add:'-2' and i < pagination.number|add:'2' %}
                       <li class="page-item">
                         <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                       </li>
                     {% endif %}
                 {% endfor %}
                 {% if pagination.has_next %}
                     <li class="page-item">
                        <a href="?page={{ pagination.next_page_number }}" class="page-link">&rsaquo;</a>
                     </li>
                     <li class="page-item">
                        <a href="?page={{ pagination.paginator.num_pages }}" class="page-link">&raquo;</a>
                     </li>
                   {% else %}
                         <li class="page-item disabled">
                        <a class="page-link">&rsaquo;</a>
                     </li>
                      <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                      </li>
                 {% endif %}
                 </ul></nav></center></div></div></div></div></div>
        </div>
                </div>
            </div></div>
            </div>
        </div>


{% endblock %}